services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    user: 1000:1000
    group_add:
      - '989' # render
      - '985' # video
    volumes:
      - config:/config
      - cache:/cache
      - /media/jellyfin/movies:/movies
      - /media/jellyfin/shows:/shows
      - /media/home_surveillance:/home_surveillance
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.<OWNED_DOMAIN>
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  config:
  cache:
